---
title: "Global Land and Ocean Temperature Anomalies"
author: "Juanma MN - https://github.com/JuanmaMN"
date: "17th April 2018"
output:
  html_document: default

---

```{r setup, include=FALSE}

library(ggplot2)
library(plotly)

library(readr)
Temperature <- read_csv("~/R/Temperature.csv")
View(Temperature)


Temperature$colour <- ifelse(Temperature$Value < 0, "firebrick1","steelblue")

Temperature_2<-select(Temperature,1:2)
```

## Global temperature anomaly data


[The National Oceanic and Atmospheric Administration](https://www.noaa.gov/) has published the time series of temperature anomalies.

As a project, we would like to illustrate the temperature change using plotly and ggplot.


[Data source](https://www.ncdc.noaa.gov/cag/global/time-series)

[For more information](https://www.ncdc.noaa.gov/cag/global/data-info)


```{r echo=FALSE, results='asis', warning = FALSE}
library(knitr)
library(kableExtra)

kable(Temperature_2[1:10,], "html", caption = "Sample data", align=c(rep('c', 5))) %>%  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

## Plotly



```{r pressure, echo=FALSE, warning = FALSE}



### Plotly

 plot_ly(Temperature, x=~Year, y=~Value, mode="markers", type="bar", color=~colour , text = ~paste('Year: ', Year, '</br> Value(?C): ', Value)) %>% 
   layout(title = "Global Land and Ocean Temperature Anomalies",xaxis = list(title = ""), yaxis = list(title = "anomaly(?C)"),
          annotations = 
            list(text = "Data from www.ncdc.noaa.gov ", 
                 showarrow = F, xref='paper', yref='paper', 
                 xref = 'paper', x = 0,
                 yref = 'paper', y = 1,
                 font=list(size=10, color="black"))
   )  %>% hide_legend()


```


## Gplot



```{r, echo = FALSE}



g<- ggplot(Temperature,aes(x=Year, y=Value))+
  geom_bar(stat="identity",position="identity",aes(fill = colour), show.legend = FALSE) + 
  labs(title = "Global Time Series", subtitle = "Global Land and Ocean Temperature Anomalies", caption = "based on data from www.ncdc.noaa.gov") + ylab("anomaly(?C)")+xlab("")

g



```


## Code, questions and feedback


The code for this article is publish in my [github account](https://github.com/JuanmaMN) in this [file](https://github.com/JuanmaMN/plotly/blob/master/Climate%20at%20a%20Glance).

Please feel free to reach out for any question or feedback.